Elearning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('utilisateurs.urls')),
    path('programmes/', include('programmes.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

programmes/urls.py
from django.urls import path
from programmes.views import *
app_name = "programmes"
urlpatterns = [
    path('', NiveauListView.as_view(), name="niveaulist"),
    path('<slug:slug>', MatiereListView.as_view(), name="matierelist"),
    path('<str:niveau>/<slug:slug>/', LessonListView.as_view(), name="lessonlist"),
    path('<str:niveau>/<str:slug>/create/', LessonCreateView.as_view(), name="lessoncreate"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/', LessonListViewDetail.as_view(), name="lessonlistdetail"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/update', LessonUpdateView.as_view(), name="lessonupdate"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/delete', LessonDeleteView.as_view(), name="lessondelete"),

]

utilisateurs/urls.py
from django.urls import path
from utilisateurs.views import acceuil, user_login, user_logout, register,about,start

urlpatterns = [
    path('', acceuil, name="home"),
    path('', start, name="index"),
    path('about', about, name="about"),
    path('register', register, name="register"),
    path('login', user_login, name="login"),
    path('logout', user_logout, name="logout"),
]

utilisateurs/models.py
from django.db import models
from django.contrib.auth.models import User
import os

def renomer_image(instance, filename):
    upload_to = 'image/'
    #pho.png
    ext = filename.split('.')[-1]
    if instance.user.username:
        filename = "profile_pic/{}.{}".format(instance.user.username, ext)
    return os.path.join(upload_to, filename)



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=150, blank=True)
    profile_pic = models.ImageField(upload_to=renomer_image, blank=True)

    student = 'student'
    lecturer = 'lecturer'
    parent = 'parent'

    type_user = [
        (student, 'student'),( lecturer, 'lecturer'), (parent, 'parent')
    ]

    type_profile = models.CharField(max_length=100, choices=type_user, default=student)


    def __str__(self):
        return self.user.username

utilisateurs/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class UserForm(UserCreationForm):
    class Meta():
        model = User
        fields=[
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2'
        ]
class ProfileForm(forms.ModelForm):
    class Meta():
        model = Profile
        fields = [
            'bio',
            'profile_pic',
            'type_profile'
        ]

utilisateurs/views.py
from django.shortcuts import render
from .forms import UserForm, ProfileForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.

def acceuil(request):
    return render(request, 'utilisateurs/index.html')

def about(request):
    return render(request, 'utilisateurs/about.html')

def start(request):
    return render(request, 'utilisateurs/index.html')
    
    


def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)   
        profile_form = ProfileForm(data=request.POST)
        if user_form.is_valid() and  profile_form.is_valid():
            user = user_form.save()
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered=True
            return HttpResponseRedirect('login')        

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form=UserForm()
        profile_form = ProfileForm()

    content ={
        'registered':registered,
        'form1':user_form,
        'form2':profile_form,
    }
    return render(request, 'utilisateurs/register.html', content)        
            
def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                return HttpResponse("User is desactivated ")
        else:
            return HttpResponse("Username or password incorrect") 
    else:
        return render(request, 'utilisateurs/login.html')  

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

utilisateurs/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>elearning</title>
    <style>
      .nav-link:hover:not(.navbar-brand){
        background-color: black;
        opacity: 0.8;
        
      }
      .nav-link:hover:not(.navbar-brand){
        border-radius: 12px;
        
      }
     
      .navbar{
        float: right;
      }
      
    </style>
</head>
<body>
    <div class="container">
        <div class="row1">
            <div class="col-md-12">
              <a class="navbar-brand" href="" style="color:#ff5722;"><b>BRAINTECH</b></a>
              <nav  class="navbar navbar-expand-md navbar-light bg-transparent" >
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                      <ul class="navbar-nav">
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'index' %}" style="color:#ff5722;"><b>Home</b></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'about' %}" style="color:#ff5722;"><b>About</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}" style="color:#ff5722;"><b>Register</b></a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}" style="color:#ff5722;"><b>Logout</b></a>
                             </li> 
                           {% else %}  
                           <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}" style="color:#ff5722;"><b>Login</b></a>
                        </li>
                        {% endif %} 
                        <li class="nav-item">
                            <a class="nav-link" href="#" style="color:#ff5722;"> <b>{{request.user.username}} </a></b>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'programmes:niveaulist' %}" style="color:#ff5722;"><b>Level</a></b>
                          </li>     
                      </ul>
                      {% if user.is_superuser %}
                      <a class =" nav-link" href="{% url 'admin:index' %}" style="color:#ff5722;"><b>Admin</span></a></b>
                    {%endif%}
                    </div>
                    
                  </nav>
            </div>
        </div>

       
  

        {% block content %}
        {% endblock %}

      </div>


      

        





  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>