Elearning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('utilisateurs.urls')),
    path('programmes/', include('programmes.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

programmes/urls.py
from django.urls import path
from programmes.views import *
app_name = "programmes"
urlpatterns = [
    path('', NiveauListView.as_view(), name="niveaulist"),
    path('<slug:slug>', MatiereListView.as_view(), name="matierelist"),
    path('<str:niveau>/<slug:slug>/', LessonListView.as_view(), name="lessonlist"),
    path('<str:niveau>/<str:slug>/create/', LessonCreateView.as_view(), name="lessoncreate"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/', LessonListViewDetail.as_view(), name="lessonlistdetail"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/update', LessonUpdateView.as_view(), name="lessonupdate"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/delete', LessonDeleteView.as_view(), name="lessondelete"),

]

programmes/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Niveaux(models.Model):  #level
    nom = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField()


    def __str__(self):
        return self.nom


    def save(self, *args, **kwargs):
        self.slug = slugify(self.nom)  
        super().save(*args, **kwargs)  


class Matiere(models.Model): #department
    matiere_id = models.CharField(unique=True, max_length=40)
    nom = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    niveau = models.ForeignKey(Niveaux, on_delete=models.CASCADE, related_name='matiere')  #level
    description = models.TextField(max_length=500)


    def __str__(self):
        return self.nom


    def save(self, *args, **kwargs):
        self.slug = slugify(self.nom)  
        super().save(*args, **kwargs)  

class Lesson(models.Model):  #course 
    lesson_id = models.CharField(unique=True, max_length=40)
    niveau = models.ForeignKey(Niveaux, on_delete=models.CASCADE)
    creer_par = models.ForeignKey(User, on_delete=models.CASCADE) 
    matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE, related_name='lesson')
    nom = models.CharField(max_length=100) 
    slug = models.SlugField(blank=True, null=True)
    position = models.PositiveSmallIntegerField(verbose_name='Year')  
    video = models.FileField(upload_to="Video", null=True, blank=True, verbose_name="Video")
    image = models.FileField(upload_to="img", null=True, blank=True, verbose_name="img")
    fpe = models.FileField(upload_to="Answers", null=True, blank=True, verbose_name="Answers")
    pdf = models.FileField(upload_to="PDF", null=True, blank=True, verbose_name="Question")
   

    class Meta:#this class is to order 
        ordering = ['position']

    def __str__(self):
        return self.nom


    def save(self, *args, **kwargs):
        self.slug = slugify(self.nom)  
        super().save(*args, **kwargs)  

    def get_absolute_url(self):
        return reverse("programmes:lessonlist", kwargs={"slug": self.matiere.slug, "niveau": self.niveau.slug})


class Commentaire(models.Model):
    nom_lesson = models.ForeignKey(Lesson, null=True, on_delete=models.CASCADE, related_name='comments')
    nom_comm = models.CharField(max_length=100, blank=True)
    # reponse = models.ForeignKey('Commentaire', null=True, blank=True, on_delete=models.CASCADE, related_name='reponses')
    auteur = models.ForeignKey(User, on_delete=models.CASCADE)
    corps = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.nom_comm = slugify("commented by " + str(self.auteur) + "at " + str(self.date_added) )
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nom_comm

    class Meta:
        ordering = ['-date_added']        


class Reponse(models.Model):
    nom_comm = models.ForeignKey(Commentaire, on_delete=models.CASCADE, related_name='reponses')      
    corps = models.TextField(max_length=500)  
    auteur = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "reply to" + str(self.nom_comm.nom_comm)

programmes/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from .models import *
from django.views.generic import DetailView, ListView, DeleteView, UpdateView, CreateView, FormView
from .form import LessonForm, ComForm, RepForm
from django.urls import reverse_lazy

class NiveauListView(ListView):
    context_object_name = 'niveaux'
    model = Niveaux
    template_name = 'programmes/niveaulist.html'


class MatiereListView(DetailView):
    context_object_name = 'niveau'
    model = Niveaux
    template_name = 'programmes/matierelist.html'

class LessonListView(DetailView):
    context_object_name = 'matieres'
    model = Matiere
    template_name = 'programmes/lessonlist.html'




class LessonListViewDetail(DetailView, FormView):
    context_object_name = 'lesson'
    model = Lesson
    template_name = 'programmes/lessonlistdetail.html'
    form_class = ComForm
    second_form_class = RepForm
    

    def get_context_data(self, **kwargs):
        context = super(LessonListViewDetail, self).get_context_data(**kwargs)

        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()

        return context  



    def form_valid(self, form):
            self.object = self.get_object()
            fd = form.save(commit=False)
            fd.auteur = self.request.user
            #fd.nom_lesson = self.object.comments.nom
            fd.nom_lesson_id = self.object.id
            fd.save()
            return HttpResponseRedirect(self.get_success_url())


    def form_valid2(self, form):
        self.object = self.get_object()
        fd = form.save(commit=False)
        fd.auteur = self.request.user
        fd.nom_comm_id = self.request.POST.get('comment_id',)
        fd.save()   
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        self.object = self.get_object.filter(matiere=matiere, complete=False).first()
        if not matiere : matiere.objects.create(matiere=matiere, complete=False)
        niveau = self.object.niveau
        matiere = self.object.matiere
        return reverse_lazy('programmes:lessonlistdetail', kwargs={
            'niveau':niveau,
            'matiere':matiere,
            'slug':self.object.slug
        })


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.form_class
            form_name = 'form'

        else:
            form_class = self.second_form_class
            form_name = 'form2'  
        form = self.get_form(form_class)

        if form_name=='form' and form.is_valid():
            print('new comment')
            return self.form_valid(form)

        if form_name=='form2' and form.is_valid():
            print('new reply')
            return self.form_valid2(form)  


               
                  







class LessonCreateView(CreateView):
    form_class = LessonForm
    context_object_name = 'matieres'
    model = Matiere
    template_name = 'programmes/lessoncreate.html' 

    def get_success_url(self):
        self.object = self.get_object()
        niveau = self.object.niveau
        return reverse_lazy('programmes:lessonlist', kwargs={'niveau':niveau, 'slug':self.object.slug})

    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        ls = form.save(commit=False)
        ls.creer_par = self.request.user
        ls.niveau = self.object.niveau
        ls.matiere = self.object
        ls.save()
        return HttpResponseRedirect(self.get_success_url())

class LessonUpdateView(UpdateView):
    fields = ('nom', 'position', 'pdf', 'fpe')
    context_object_name = 'lesson'
    model = Lesson
    template_name = 'programmes/lessonupdate.html'

class LessonDeleteView(DeleteView):
    model = Lesson
    context_object_name = "lesson"
    template_name = 'programmes/lessondelete.html'
    
    def get_success_url(self):
        niveau = self.object.niveau
        matiere = self.object.matiere
        return reverse_lazy("programmes:lessonlist", kwargs={'niveau':niveau, 'slug':matiere.slug})

    

        

programmes/templates/programmes/lessoncreate.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block content %}

<body style="background-color:#fffff0 ;">
<section id="best-features" class="text-center">
    <br> 
    <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Create a Course</h2>
</section>
<form method="post" enctype="multipart/form-data">
    <div class="form-group">
   <form method="POST">
       {% csrf_token %}
       {{ form|crispy }}
       <input class="btn btn-success btn-lg btn-block" type="submit" value="Confirm Creation">
    </div>
  </form>
</body>
{% endblock %}

programmes/templates/programmes/lessondelete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
</style>


<body style="background-color:#fffff0 ;">

<section id="best-features" class="text-center">
    <br>
    <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">DELETE {{lesson.nom}}</h2>
    <!-- class row for description-->
    <div class="row d-flex justify-content-center mb-4">
      <!-- class column -->
      <div class="col-md-8">
    <!-- divider -->
    <hr style="color:#ff5722;">
      </div>
    </div>
</section>

<h1 style="color:#ff5722;">Are you sure you want to delete ?</h1>

   <form method="POST">
       {% csrf_token %}
       <div class="row">
        <div class="col-md-4">
                <input type="submit" value="DELETE" class="btn btn-danger btn-block">
            </div>
            <div class="col-md-4">
       <a href="{% url 'programmes:lessonlistdetail' slug=lesson.slug matiere=lesson.matiere.slug niveau=lesson.niveau.slug %}" class="btn btn-warning btn-block">Cancel operation</a>
    </div>
</div>
</form>
</body>

{% endblock %}

programmes/templates/programmes/lessonlist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
  .btn{
    background-color: #00bcd4;
    border-radius: 12px;
  }
  .btn:hover{
    background-color: black;
    opacity: 0.8;
  }
  </style>
<body id="img" class="containe-fluid" style="background-image: url('{% static 'images/martin.jpg' %}')";>

<header class="info-header">
    <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
      <div class="row d-flex justify-content-center text-center">
        <div class="col-md-10 text-white">
          <!-- heading -->
          <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" >Courses per year</h2>
          </div>

          <!-- divider -->
          <hr style="color:#ff5722;">

  </header>
  <div class="row d-flex justify-content-center mb-3">
    {% for lesson in matieres.lesson.all  %}
    {% if user.is_authenticated  %}
      <div class="card mb-5 mr-4 ml-4" style="max-width: 320px; border-radius: 25px;">
        <div class="row no-gutters">
                     <div class="card-body" >
                        <center><h5 class="card-title" style="color:#ff5722;">{{ lesson.nom }}: Year-{{lesson.position}} </h5>
                        <p class="card-text"><small class="text-muted"></small></p>
                       <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
                        <a href="{% url 'programmes:lessonlistdetail' slug=lesson.slug matiere=matieres.slug niveau=matieres.niveau.slug %}"class="btn btn-primary" >Get Materials</button></a></center>
                     </div>
                   </div>
         </div>
        {% else %}
         <p> To view course you need to login <a href="{% url 'login' %}"> Login</a></p>
         {% endif %}
      
         {% endfor %}

   
      </div>
  </div>
  <div class="row d-flex justify-content-center mb-3">
    {% if user.userprofileinfo.user_type == 'teacher' or user.is_superuser %}
    <a href="{% url 'programmes:lessoncreate' niveau=matieres.niveau.slug slug=matieres.slug %}"><button type="button" class="btn btn-success btn-lg btn-bloc" > Add new Lesson </button> </a>
    {% endif %}
  </div>
</body>


{% endblock %}

programmes/templates/programmes/lessonlistdetail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block content %}
<style>
  button{
    border-radius: 6px;
    border: 0;
    
  }
  button:hover{
    background-color:gray;
    opacity: 4;

  }
  body{
    background-color: #FFFFF0;
  }
  
</style>
<body >

 <section class="text-center">
        <h2 class="mb-0 mt-5 font-weight-bold" style="color:#ff5722;">Course Details</h2>
        <div class="row d-flex justify-content-center mb-3">
          <blockquote class="blockquote mt-0">
        <footer class="blockquote-footer">The course {{ lesson.nom }} was created by  {{ lesson.creer_par }}</cite></footer>
        </blockquote>
       </div>
       <!-- image -->
    <div class="row d-flex justify-content-center mb-3">
        <div >
              <image>
                  <img src="{{lesson.image.url}}" >
              </image>
        </div>
      </div>
        <!-- download cards -->
    <div class="row d-flex justify-content-center ">
        <!-- download answers -->
                  <div class="col-md-4 mb-4 mt-4">
                    <div class="card box-shadow-hover">
                      <div class="card-body">
                        <h5 class="card-title">Download Answer</h5>
                        {% if lesson.fpe %}
                        <a href="{{lesson.fpe.url}}" download>
                        <button type="button" class="button-les"><span>Get Files</span></button>
                        </a>
                        {% else %}
                        <p class="card-text" > No Answer available</p>
                        {% endif %}
  
                      </div>
                    </div>
                  </div>

                    <!-- download questions -->
                <div class="col-md-4 mb-4 mt-4">
                        <div class="card box-shadow-hover">
                          <div class="card-body">
                            <h5 class="card-title">Download paper</h5>
                            {% if lesson.pdf %}
                            <a href="{{lesson.pdf.url}}" download>
                            <button type="button" class="button-les"><span>Get Files</span></button>
                            </a>
                            {% else %}
                            <p class="card-text">pdf not available</p>
                            {%endif%}
      
                          </div>
                        </div>
                      </div>
                </section>
 <section>
                       <!-- update and delete button -->
          <div class="row  justify-content-center mb-3 mt-3">
        {% if user.userprofileinfo.user_type == 'teacher' or user.is_superuser %}
        <a href="{% url 'programmes:lessonupdate' niveau=lesson.niveau.slug matiere=lesson.matiere.slug slug=lesson.slug %}"class="btn btn-warning" style="background-color:red;"> Update course</a>
          </div>
        <div class="row justify-content-center mb-3 mt-3">
         <a href="{% url 'programmes:lessondelete' niveau=lesson.niveau.slug matiere=lesson.matiere.slug slug=lesson.slug %}"class="btn btn-warning" style="background-color:red;"> Delete course</a>
        </div>
        {% endif %}
</section>

        <hr class="my-5" style="color:#ff5722;">

        <!-- Comments section -->
<section >
        <h2 class="mb-4 mt-5 font-weight-bold" style="color:#ff5722;">Questions And Comment</h2>
        <h4 class="mt-2 font-weight-bold" style="color:#ff5722;">Post your comment or question below:</h4>
        <br><br>
        <div class="container row">
          <div class="col-md-6">
                                  <form method="post">
                                        <div class="form-group">
                                        {% csrf_token %}
                                        {{form|crispy}}
                                        <input type="submit" name="form" value="Add Comment" class="btn btn-primary btn-sm">
                                        </div>
                                  </form>
    
          </div>
        </div>
        <div class="row">

        <h4>Post your comments below.</h4>

        <form  method="post">
                {% csrf_token %}
                <div class="form-group">
                        {{ form.as_p }}
                        <input type="submit" name="form" value="comment" class="btn btn-primary btn-sm">

                </div>
        </form>

        {% for comment in lesson.comments.all  %}
        <div class="col-md-8 mt-2 mb-2">
                <div class="media border p-3">
                
                    <div class="media-body">
                <h4> {{ comment.auteur }} <small> <i> posted on {{ comment.date_added }}</i></small></h4>
                <p>{{ comment.corps }}</p>
                {% for reponse in comment.reponses.all  %}
                <div class="media p-3">
                        
                <div class="media-body">
                         <h5> {{ reponse.auteur }} <small> <i> posted on {{ reponse.date_added }}</i></small></h5>
                         <p>{{ reponse.corps }}</p>

                        </div>
                </div>
    {% endfor %}

      <!-- form to post reply -->
      <form method="POST">
        <input type="hidden" name="comment.id" value="{{comment.id}}">
        <input type="hidden" name="comment.comm_name" value="{{comment.comm_nom}}">
        {% csrf_token %}
        {{form2.as_p}}
        <input type="submit" name="form2" value="Add Reply" class="btn btn-warning btn-sm">
  </form>
</div>
</div>
</div>
{% endfor %}
</div>


</section>

{%endblock%}
</body>
            

programmes/templates/programmes/lessonupdate.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<body style="background-color:#fffff0 ;">
<section id="best-features" class="text-center">
    <br>
    <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Update {{lesson.nom}}</h2>
</section>


   <form method="POST" >
       {% csrf_token %}
       {{ form|crispy }}
       <div class="row">
        <div class="col-md-4">
                <input type="submit" value="Update" class="btn btn-warning btn-block">
        </div>
        <div class="col-md-4">
       <a href="{% url 'programmes:lessonlistdetail' slug=lesson.slug matiere=lesson.matiere.slug niveau=lesson.niveau.slug %}" class="btn btn-danger btn-block">Cancel  Update</a>
    </div>
</div>
</form>
</body>


{% endblock %}

programmes/templates/programmes/matierelist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
.btn{
  background-color: #00bcd4;
  border-radius: 12px;
  border-color: black;
  
}
.btn:hover{
  background-color: black;
  opacity: 0.8;
}

</style>

<body id="img" class="containe-fluid" style="background-image: url('{% static 'images/thougha.jpg' %}')";>

<header class="info-header">
    <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
      <div class="row d-flex justify-content-center text-center">
        <div class="col-md-10 text-white">
          <!-- heading -->
          <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Departments </h2>
          <div class="row d-flex justify-content-center text-center">
            
          </div>

          <!-- divider -->
          <hr style="color:#ff5722;">

  </header>

      
    <!-- class row2 for cards -->
    <div class="row d-flex justify-content-center ">
        {% for matiere in niveau.matiere.all  %}
        <div class="card mb-5  ml-4 box-shadow-hover" style="max-width:350px; border-radius: 25px;">
          <div class="row no-gutters">
                    <div class="col-md-12">
                      <div class="card-body">
                        <center><b><h5 class="card-title" style="color:#ff5722;">{{ matiere.nom }}</b></h5>
                        <p class="card-text"><small class="text-muted"></small></p>
                         <a href="{% url 'programmes:lessonlist' slug=matiere.slug  niveau=niveau.slug %}" class="btn btn-primary"> Get courses</button></a></center>
                      </div>
                    </div>
          </div>
          </div>
        {% endfor %}
        </div>
</body>

      

{% endblock %}

programmes/templates/programmes/niveaulist.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<style>
  .btn{
    background-color: #00bcd4;
    border-radius: 12px;
    border-color: black;
  }
  .btn:hover{
    background-color:black;
    opacity: 0.8;
  }

</style>
<body id="img" class="container-fluid" style="background-image: url('{% static 'images/bec1.jpg' %}')"  ; >
<!-- section 1 for level-->
<section id="best-features" class="text-center">
              <h2 class="mb-5 mt-5 font-weight-bold" style="color:#ff5722;">Dive Into Revision</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p > <h5 style="color: #ff5722;"><b> Welcome to our level board, choose your appropriate level and get started !</b></h5></p>
                </div>
              </div>
              <!-- class row2 for cards -->
              <div class="row">
            {% for niveau  in niveaux  %}
                <div class="col-md-4  justify-content-center">
                  <div class="card card-std text-center" style="width: 300px; border-radius: 25px; height: 150px;">
                    <div class="card-body text-center">
                      <h4 class="card-title" style="color:#ff5722;"><b>{{ niveau.nom }}</b></h4>
                      <br>
                      <!-- <p class="card-text">{{niveau.description|truncatechars:75}}</p> -->
                      {% if user.is_authenticated %}
                      <a href="{% url 'programmes:matierelist' slug=niveau.slug %}" class="btn btn-primary" >Lets get started</a>
                      {%else%}
                      <p>Register or login to start learning</p>
                      <a href="{% url 'login' %}" class="btn btn-primary" style="background-color:#00bcd4;">Login</a>
                      <a href="{% url 'register' %}" class="btn btn-primary" style="background-color:#00bcd4;">Register</a>
                      {%endif%}
                    </div>
                  </div>
                </div>
                {% endfor %}

            </div>
        </section>
      </body>
        
        {%endblock%}